### ISSUE TITLE
Site Page wise User

### ISSUE THREAD

**Issue by sunnykadam** [ramonck/PowerAutomate#1]
Hello,

Is there any way I can find the list of users by page visited ?

Thank you.

Regards,
Sunny

**Comment by ramonck** [comment]
Hi @sunnykadam ,
Out of the box Microsoft provides some analytics: https://learn.microsoft.com/en-us/power-platform/admin/analytics-powerapps
If you need more information, I recommend creating a custom dashboard from Power Platform data: https://learn.microsoft.com/en-us/power-platform/admin/build-custom-reports?source=recommendations

**Comment by sunnykadam** [comment]
@ramonck  Sorry for misunderstanding. I need to see users who has visited the sharepoint pages and not powerapps. So along with Principal name, can we get the page name as well ?
